filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /var/log/*.log
    json:
    keys_under_root: true
    add_error_key: true

output.logstash:
  enabled: true
  hosts: ["movies-logstash:5044"]