name: test-auth
services:
  test-auth-postgres:
    image: postgres:16.4
    container_name: test-auth-postgres
    restart: always
    env_file:
        - src/.test.env
    expose:
        - 5432
    healthcheck:
      test: [ "CMD", "pg_isready -U app -d movies_database" ]
      interval: 10s
      timeout: 3s
      retries: 3
  
  test-auth-redis:
    image: redis:7.4.0
    container_name: test-auth-redis
    restart: always
    env_file:
        - src/.test.env
    expose:
        - 6379
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      interval: 2s
      timeout: 60s
      retries: 5
