services:
  content:
    container_name: mongo-content
    build: src
    env_file:
      - src/.env
    restart: always
    command: bash -c "
      uvicorn app.main:app --host 0.0.0.0 --port 8001"
#    networks:
#      - movies-network



#networks:
#  movies-network:
#    name: movies-network
#    external: true