services:
  postgres:
    image: postgres:16
    container_name: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./dbs/postgres/data:/var/lib/postgresql/data
    env_file:
      - ./.env
    restart: always

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    ports:
      - "5050:80"
    volumes:
      - ./dbs/pgadmin/data:/var/lib/pgadmin
    env_file:
      - ./.env
    restart: always