"""partition_session

Revision ID: ab2aab9e78f9
Revises: 7bdb58b01cc0
Create Date: 2024-09-22 12:15:09.256540

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ab2aab9e78f9"
down_revision: str | None = "da0c5e1346ff"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("session")

    op.create_table(
        "session",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("refresh_token_id", sa.Uuid(), nullable=False),
        sa.Column("user_agent", sa.String(length=256), nullable=True),
        sa.Column(
            "id",
            sa.Uuid(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["refresh_token_id"],
            ["refreshtoken.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id", "created_at"),
        postgresql_partition_by="RANGE (created_at)",
    )

    op.execute(
        """CREATE TABLE IF NOT EXISTS "user_session_y2024m09" PARTITION OF "session" FOR VALUES FROM ('2024-09-01') TO ('2024-09-30')"""
    )
    op.execute(
        """CREATE TABLE IF NOT EXISTS "user_session_y2024m10" PARTITION OF "session" FOR VALUES FROM ('2024-10-01') TO ('2024-10-31')"""
    )
    op.execute(
        """CREATE TABLE IF NOT EXISTS "user_session_y2024m11" PARTITION OF "session" FOR VALUES FROM ('2024-11-01') TO ('2024-11-30')"""
    )
    op.execute(
        """CREATE TABLE IF NOT EXISTS "user_session_y2024m12" PARTITION OF "session" FOR VALUES FROM ('2024-12-01') TO ('2024-12-31')"""
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("session")

    op.create_table(
        "session",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("refresh_token_id", sa.Uuid(), nullable=False),
        sa.Column("user_agent", sa.String(length=256), nullable=True),
        sa.Column(
            "id",
            sa.Uuid(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["refresh_token_id"],
            ["refreshtoken.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###
